### ISSUE TITLE
Creating Profile Page

### ISSUE THREAD

**Issue by RATDOTL** [honganji/kenshow#6]
Creating a profile creation screen after signing in.
Items,
User name
Search ID
icon
Phone number (SMS authentication) 

サインイン後のプロフィール作成画面の作成。
項目は、
ユーザーネーム
検索用ID
アイコン
電話番号(SMS認証)

**Comment by atahatah** [comment]
It's still a work in progress, but I thought I should share it once, so I committed it.
If you have any thoughts on how to separate programs or file structure, please share them.
まだまだ途中やけど、一旦共有しとくべきだと思ったからコミットした
プログラムの切り分け方とかファイル構成についてなんか思うところがあったら共有して
